-- CREATE TYPE post_category AS ENUM (
--   'Listicle',
--   'How-to',
--   'News',
--   'Interview',
--   'Story'
-- )

CREATE TABLE zentube_posts (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    content TEXT,
    -- category post_category,
    category TEXT,
    file_name TEXT,
    author_id INTEGER REFERENCES zentube_users(id)
    ON DELETE SET NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);