CREATE TABLE zentube_comments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    text TEXT NOT NULL,
    comment_time NUMERIC (12, 6) DEFAULT 0 NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    post_id INTEGER
        REFERENCES zentube_posts(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER
        REFERENCES zentube_users(id) ON DELETE CASCADE NOT NULL
);
